# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-02-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('barrio', smart_selects.db_fields.ChainedForeignKey(chained_field='ciudad', chained_model_field='ciudad', on_delete=django.db.models.deletion.CASCADE, to='persona.Barrio')),
                ('ciudad', smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento', on_delete=django.db.models.deletion.CASCADE, to='persona.Ciudad')),
                ('departamento', smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='persona.Departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Pais')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
